name: controle
description: App de controle financeiro
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # 🔥 SUPABASE (backend)
  supabase_flutter: ^2.12.0

  # 🔥 STATE MANAGEMENT
  flutter_riverpod: ^2.5.0

  # 🔥 GRÁFICOS (dashboard)
  fl_chart: ^1.2.0

  # 🔥 PDF
  pdf: ^3.12.0
  printing: ^5.14.3

  # 🔥 FORMATOS
  intl: ^0.18.0
  app_links: ^6.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

  # 🔥 ÍCONE DO APP
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/icon.png

# 🔥 CONFIG DO ÍCONE
flutter_icons:
  android: true
  ios: false
  image_path: "assets/icon.png"